server:
  servlet:
    context-path: /api
  port: 8001

spring:
  datasource:
    url: '${DB_URL}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: 'false'
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect

  security:
    user:
      name: user
      password: xxxx
    profiles:
      active: test
